name: motifmamba-fig5
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - tensorboard
  - pytorch
  - pytorch-cuda=11.8
  - pip:
      - einops
      - causal-conv1d>=1.4.0
      - mamba-ssm
